version: build-{build}.{branch}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: "8ytgwuh2SNKTbSi+N8Mm0g=="
  DOCKER_PASS:
    secure: "/pXE9T3huXIXgID8jW1rfA=="
  matrix:
    - version: 5.6
      variant: nanoserver-sac2016
      DOCKER_USER:
        secure: "8ytgwuh2SNKTbSi+N8Mm0g=="
      DOCKER_PASS:
        secure: "/pXE9T3huXIXgID8jW1rfA=="
    - version: 5.6
      variant: windowsservercore-ltsc2016
    - version: 5.7
      variant: nanoserver-sac2016
    - version: 5.7
      variant: windowsservercore-ltsc2016

install:
  - ps: |
      [Environment]::SetEnvironmentVariable('dockerImage', ('docker-mysql:{0}' -f $env:version), [EnvironmentVariableTarget]::Process);
      [Environment]::SetEnvironmentVariable('buildDirectory', ('{0}/{1}' -f $env:version, $env:variant), [EnvironmentVariableTarget]::Process);

build_script:
  - cmd: appveyor-retry docker build --pull -t %dockerImage% %buildDirectory%

after_build:
  - ps: docker images

test_script:
  - cmd: docker run --rm %dockerImage% MySQL --version

deploy_script:
  - docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - docker push rafaelpdes/mysql
