version: build-{build}.{branch}
image: Visual Studio 2017

environment:
  matrix:
    - version: 5.6
      variant: windowsservercore-ltsc2016
    - version: 5.6
      variant: nanoserver-sac2016
    - version: 5.7
      variant: windowsservercore-ltsc2016
    - version: 5.7
      variant: nanoserver-sac2016

install:
  - ps: |
      [Environment]::SetEnvironmentVariable('dockerImage', ('docker-mysql:{0}' -f $env:version), [EnvironmentVariableTarget]::Process);
      [Environment]::SetEnvironmentVariable('buildDirectory', ('{0}/{1}' -f $env:version, $env:variant), [EnvironmentVariableTarget]::Process);
build_script:
  - cmd: appveyor-retry docker build --pull -t %dockerImage% %buildDirectory%

after_build:
  - ps: docker images

test_script:
  - cmd: docker run --rm %dockerImage% MySQL --version