version: build-{build}.{branch}
    
# Skipping commits with particular message or from specific user
skip_commits:
  message: /wip/

image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: 8ytgwuh2SNKTbSi+N8Mm0g==
  DOCKER_PASS:
    secure: /pXE9T3huXIXgID8jW1rfA==
  DOCKER_IMAGE_TAG_PREFIX: rafaelpdes/mysql
  LATEST: 5.7.21-nanoserver-sac2016

install:
  - ps: |
      $DOCKER_IMAGE_TAG_SUFFIX = $null
      echo "$env:APPVEYOR_REPO_BRANCH"
      if ($env:APPVEYOR_REPO_BRANCH -eq "master") {
        $DOCKER_IMAGE_TAG_SUFFIX = $env.LATEST
      } else {
        $DOCKER_IMAGE_TAG_SUFFIX = $env:APPVEYOR_REPO_BRANCH
      }
      
      $v1,$v2,$release,$variant = $DOCKER_IMAGE_TAG_SUFFIX.Split('.').Split('-', 2)
      $version = "$v1.$v2"
      
      [Environment]::SetEnvironmentVariable('dockerImage', ('{0}:{1}' -f $env:DOCKER_IMAGE_TAG_PREFIX, $DOCKER_IMAGE_TAG_SUFFIX), [EnvironmentVariableTarget]::Process);
      [Environment]::SetEnvironmentVariable('buildDirectory', ('{0}/{1}' -f $version, $variant), [EnvironmentVariableTarget]::Process);

build_script:
  - cmd: appveyor-retry docker build --pull -t %dockerImage% %buildDirectory%

after_build:
  - ps: |
      if ($env:APPVEYOR_REPO_BRANCH -eq "master") {
        docker tag "$env:dockerImage $env:DOCKER_IMAGE_TAG_PREFIX:latest"
      }
      docker images

test_script:
  - cmd: docker run --rm %dockerImage% MySQL --version

deploy_script:
  - ps: |
      docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
      docker push "$env:DOCKER_IMAGE_TAG_PREFIX"
